/**
 * Reason codes for invalid S1 signals.
 * These are stored as strings in the DB (flexible),
 * but enforced as an enum in TypeScript (type-safe).
 */
export enum SignalReasonCode {
  ACCEPTANCE_INSUFFICIENT = 'ACCEPTANCE_INSUFFICIENT',
  ENGULFING_INSUFFICIENT = 'ENGULFING_INSUFFICIENT',
  LIQUIDITY_PRESENT = 'LIQUIDITY_PRESENT',
  OPPOSITE_IMBALANCE_VALID = 'OPPOSITE_IMBALANCE_VALID',
  ASIA_RANGE_NOT_FINALIZED = 'ASIA_RANGE_NOT_FINALIZED',
  OUTSIDE_OPERATIVE_WINDOW = 'OUTSIDE_OPERATIVE_WINDOW',
  INSUFFICIENT_BARS = 'INSUFFICIENT_BARS',
}
